spring.application.name=student-analytics

# database
    # database address
spring.datasource.url=jdbc:postgresql://turntable.proxy.rlwy.net:48050/railway 
    # username for database
spring.datasource.username=postgres
    # password for database (hardcoded!)
spring.datasource.password=FxYMAxsEUECzucrsWSVqnaEbkEOSfipZ
    # tells Spring which Driver to use, this is the PostgreSQL Driver dependency that was initially selected
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
    # tells Hibernate what to do with tables when started, "update" will create a table if it doesn't exist or update a table if it does exist
spring.jpa.hibernate.ddl-auto=update
    # prints every SQL query to terminal, useful for debugging
spring.jpa.show-sql=true
    # tells Hibernate to generate a PostgreSQL specific code because every base has slightly different SQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# server port
    # the port location where Tomcat server is listening
server.port=8080